### ISSUE TITLE
Mac:Can't run the "jq" file in the bin folder

### ISSUE THREAD

**Issue by sleep2death** [kairyu/tkg-toolkit#2]
I'm using mac to run the "setup.sh" in Linux folder, and there is an error:"-bash: ./jq: cannot execute binary file", how can i fix it?

**Comment by kairyu** [comment]
The jq shipping with tkg-toolkit in linux folder is a binary file pre-compiled for Linux system.
You can download the OS X version [here](https://stedolan.github.io/jq/download/) and replace the original one.

I have plan to support mac but I have no time to test it.
If you confirmed the bash scripts work on mac too, I will update a formal support for mac.

**Comment by AdamYoung1234** [comment]
I tested jq 1.5, and it works well in OS X 10.10. ;)

**Comment by azhang** [comment]
I tested on mac, with these steps: https://github.com/kairyu/tkg-toolkit/pull/7
