### ISSUE TITLE
Mac: ./reflash.sh: line 44: declare: -g: invalid option

### ISSUE THREAD

**Issue by hging** [kairyu/tkg-toolkit#4]
declare -g is also not available on any EL6 (BASH 4.1.2) or EL5 (BASH 3.2.25) platforms. This just broke our whole infrastructure!

It appears that the declare -g flag was added in BASH 4.2, I assume this wasn't tested?

I change it to
```
export "$line"
```
it works well :)

**Comment by kairyu** [comment]
Finally I decided to use ```eval "$line"``` instead of ```export "$line"```. Fixed it by 326854b3a5f958b59078fc9d55496507a868bee6

Thank you.
